[build]
  publish = "public/"
  # Removing _build-dependency-hl-3.0/ folder because it's just used as source for 'npm run build'
  # and other Hugo pages.
  command = "hugo && npm run build && npm test && rm -rf public/_build-dependency*"

[build.environment]
  HUGO_VERSION = "0.88.1"
  NODE_VERSION = "14.18.0"
  # Netlify functions runtime version
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[functions]
  node_bundler = "esbuild"

# Enable SPA functionality for License builder page
# Urls like "/build/hl-bsd-eco", should always
# hit the javascript code which will select proper
# modules to show.
[[redirects]]
  from = "/build/hl*"
  to = "/build/index.html"
  status = 200
  force = true

# Proxy requests to on-demand builder so that
# we can return configured license texts for
# markdown and plaintext.
[[redirects]]
  from = "/version/3/0/*"
  to = "/.netlify/functions/download-license"
  status = 200